steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t', 'carlosgomezpag/demo-cloud-builder', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['login','-u', 'carlosgomezpag', '-p', 'nhcdocker@pag']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'carlosgomezpag/demo-cloud-builder']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coyotewell'
timeout: 660s
